/**
 * Realistic Mock Fixtures for SIH26034 Legal Metrology Packaged Commodities Compliance Scanner
 * Strictly matching backend schemas in app/schemas/common.py, compliance.py, extraction.py, inspection.py
 *
 * Covers 11 Scenarios:
 * 1. FIXTURE-01-COMPLIANT: Fully compliant product (Parle-G Gold Glucose Biscuits)
 * 2. FIXTURE-02-VIOLATION: Product with potential violations (Missing date & consumer care)
 * 3. FIXTURE-03-LOW-CONFIDENCE: Product requiring manual review (Low OCR confidence on MRP tax clause)
 * 4. FIXTURE-04-MRP-CONFLICT: Product with conflicting MRP observations (Front ₹190 vs Back ₹210)
 * 5. FIXTURE-05-QTY-CONFLICT: Product with conflicting Net Quantity observations (Front 500g vs Back 450g)
 * 6. FIXTURE-06-MED-DEVICE-PENDING: Medical device confirmation gate pending (Fix 2)
 * 7. FIXTURE-07-MED-DEVICE-CONFIRMED: Confirmed medical device (PCR rules suppressed to NOT_APPLICABLE)
 * 8. FIXTURE-08-NOT-DETECTED-COVERAGE: Incomplete surface coverage (Missing declarations -> prompt to scan other faces)
 * 9. FIXTURE-09-ANALYSIS-FAILED: Technical CV/OCR failure (Severe blur/corruption -> ANALYSIS_FAILED)
 * 10. FIXTURE-10-SMALL-PACKAGE: Small package exemption (<= 10g under Rule 26 -> NOT_APPLICABLE)
 * 11. FIXTURE-11-PAN-MASALA-ROUTED: Pan Masala router (Exemption disabled by G.S.R. 881(E) -> full compliance checked)
 */

export const RULE_METADATA = {
  "REQ-MVP-01": {
    name: "Mandatory Declaration Presence",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 6(1); exemption under Rule 26",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "VERIFIED — VERBATIM",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-02": {
    name: "Maximum Retail Price (MRP) Layout",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 2(m), Rule 6(1)(e)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "VERIFIED — VERBATIM",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-03": {
    name: "Net Quantity Metric Unit Validation",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 13(1), (4), (5)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "VERIFIED — VERBATIM",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-04": {
    name: "Net Quantity Unit-Switching Boundary",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 13(2), (3) + Proviso",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-05": {
    name: "Prohibited Quantity Qualifiers",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 12(6)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-06": {
    name: "Date Declaration & Overwriting Proviso",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 6(1)(d) + Proviso",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-07": {
    name: "Consumer Care Contact Details",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 6(2)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-08": {
    name: "Manufacturer Address Block Layout",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 10(1) Explanation",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-09": {
    name: "Foreign Importer PDP Address Match",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 10(1) Proviso 2",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-10": {
    name: "Pan Masala Compliance Router",
    source: "03_PCR_Second_Amendment_2025.pdf",
    clause: "Rule 26(a) Second Proviso",
    gsr_number: "G.S.R. 881(E) (2nd Amendment 2025)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-11": {
    name: "Medical Devices Compliance Router",
    source: "02_PCR_Amendment_2025_24-10-2025.pdf",
    clause: "Rule 2(h)/7(2)/7(3) Provisos",
    gsr_number: "G.S.R. 778(E) (Amendment 2025)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-12": {
    name: "Non-Standard Pack Size Disclaimer",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 5, Proviso",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "VERIFIED — VERBATIM",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-13": {
    name: "Prohibition of Individual Correction Stickers",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 6(3)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "VERIFIED — VERBATIM",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-14": {
    name: "Quantity Clearance Space (Quiet Zone)",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 8(1), Proviso",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
  "REQ-MVP-15": {
    name: "Readability & Text Contrast",
    source: "01_Packaged_Commodities_Rules_2011.pdf",
    clause: "Rule 9(1) + Proviso (a)",
    gsr_number: "G.S.R. 202(E) (Principal)",
    verification_status: "CONFIRMED",
    last_verified: "2026-09-05",
  },
};

export const MOCK_FIXTURES = {
  // ---------------------------------------------------------------------------
  // 1. FULLY COMPLIANT PRODUCT
  // ---------------------------------------------------------------------------
  "insp-001": {
    inspection: {
      id: "insp-001",
      created_at: "2026-09-06T10:15:00Z",
      updated_at: "2026-09-06T10:16:30Z",
      status: "REPORT_GENERATED",
      compliance_status: "COMPLIANT",
      product_name: "Parle-G Gold Glucose Biscuits",
      brand_name: "Parle",
      commodity_category: "Biscuits",
      inspector_id: "insp_delhi_01",
      image_coverage: { front: true, back: true, side: true, top: true },
      notes: "Routine retail shelf check at Supermarket Sector 18. All declarations verified.",
      images_count: 3,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-001-f",
        inspection_id: "insp-001",
        file_name: "parle_front.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 342100,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fef3c7'/><rect x='40' y='40' width='520' height='320' rx='8' fill='%23fde68a' stroke='%23d97706' stroke-width='2'/><text x='300' y='100' font-family='sans-serif' font-size='26' font-weight='bold' fill='%2392400e' text-anchor='middle'>Parle-G Gold</text><text x='300' y='140' font-family='sans-serif' font-size='16' fill='%23b45309' text-anchor='middle'>Glucose Biscuits (Front Display Panel)</text><rect x='80' y='280' width='160' height='40' fill='%23fef9c3' stroke='%23ca8a04' stroke-width='1.5'/><text x='160' y='305' font-family='sans-serif' font-size='16' font-weight='bold' fill='%23854d0e' text-anchor='middle'>Net Wt: 100 g</text></svg>",
        uploaded_at: "2026-09-06T10:15:05Z",
      },
      {
        evidence_id: "ev-001-b",
        inspection_id: "insp-001",
        file_name: "parle_back.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 412500,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23f8fafc'/><rect x='40' y='30' width='520' height='340' rx='6' fill='%23ffffff' stroke='%23cbd5e1' stroke-width='2'/><text x='60' y='70' font-family='sans-serif' font-size='14' font-weight='bold' fill='%231e293b'>Mfg by: Parle Products Pvt Ltd, Vile Parle East, Mumbai 400057</text><text x='60' y='110' font-family='sans-serif' font-size='14' fill='%23334155'>Country of Origin: India</text><text x='60' y='150' font-family='sans-serif' font-size='16' font-weight='bold' fill='%230f172a'>MRP ₹ 30.00 incl. of all taxes</text><text x='60' y='190' font-family='sans-serif' font-size='14' fill='%23334155'>Mfg Date: 08/2026</text><text x='60' y='230' font-family='sans-serif' font-size='13' fill='%23475569'>Consumer Care: 1800227788 | care@parle.biz</text></svg>",
        uploaded_at: "2026-09-06T10:15:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-001",
      product_name: {
        value: "Glucose Biscuits",
        raw_text: "Parle-G Gold Glucose Biscuits",
        confidence: 0.98,
        bounding_box: { x: 50, y: 20, w: 300, h: 40 },
        location: "front",
      },
      commodity_category: {
        value: "Biscuits",
        raw_text: "Biscuits",
        confidence: 0.99,
        location: "front",
      },
      manufacturer: {
        premises: "North Level Factory Unit 4",
        street: "V.S. Khandekar Marg, Vile Parle East",
        city: "Mumbai",
        state: "Maharashtra",
        pin_code: "400057",
        raw_text: "Manufactured by: Parle Products Pvt. Ltd., North Level Factory Unit 4, V.S. Khandekar Marg, Vile Parle East, Mumbai, Maharashtra - 400057",
        confidence: 0.96,
        bounding_box: { x: 40, y: 300, w: 420, h: 80 },
      },
      country_of_origin: {
        value: "India",
        raw_text: "Country of Origin: India",
        confidence: 0.99,
        location: "back",
      },
      net_quantity: {
        value: 100.0,
        unit: "g",
        raw_text: "Net Weight: 100 g",
        confidence: 0.97,
        bounding_box: { x: 80, y: 280, w: 160, h: 40 },
        qualifiers: null,
        quiet_zone_clear: true,
        location: "front",
      },
      net_quantity_observations: [
        {
          value: 100.0,
          unit: "g",
          raw_text: "Net Weight: 100 g",
          confidence: 0.97,
          location: "front",
        },
      ],
      mrp: {
        value: 30.0,
        currency: "₹",
        tax_inclusivity: true,
        raw_text: "MRP ₹ 30.00 incl. of all taxes",
        confidence: 0.96,
        bounding_box: { x: 60, y: 130, w: 250, h: 30 },
        is_sticker: false,
        location: "back",
      },
      mrp_observations: [
        {
          value: 30.0,
          currency: "₹",
          tax_inclusivity: true,
          raw_text: "MRP ₹ 30.00 incl. of all taxes",
          confidence: 0.96,
          location: "back",
        },
      ],
      date_of_manufacture: {
        month: "08",
        year: "2026",
        raw_text: "Mfg Date: 08/2026",
        confidence: 0.95,
        is_rubber_stamped: false,
        has_overwriting: false,
      },
      consumer_care: {
        name_or_office: "Consumer Care Executive, Parle Products",
        address: "V.S. Khandekar Marg, Vile Parle East, Mumbai 400057",
        phone: "1800227788",
        email: "care@parle.biz",
        raw_text: "For consumer complaints: Contact Consumer Care Executive, Parle Products, Toll Free: 1800227788, Email: care@parle.biz",
        confidence: 0.94,
      },
      image_coverage: { front: true, back: true, side: true, top: true },
    },
    compliance: {
      inspection_id: "insp-001",
      overall_status: "COMPLIANT",
      summary_counts: {
        total_rules: 15,
        compliant: 11,
        potential_violations: 0,
        needs_manual_review: 2, // REQ-MVP-14, REQ-MVP-15 (visual aids)
        not_applicable: 2, // REQ-MVP-10 (Not Pan Masala), REQ-MVP-11 (Not Medical Device)
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T10:16:30Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-01",
          status: "COMPLIANT",
          detected_value: "Manufacturer, Commodity, Net Qty, Mfg Date, MRP",
          normalized_value: "5/5 mandatory blocks present",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "All five core statutory declaration blocks detected on submitted packaging panels.",
          explanation_for_inspector: "All five mandatory declarations (Manufacturer Address, Generic Name, Net Quantity, Manufacture Date, and MRP) have been successfully identified on the package.",
          evidence: { raw_ocr_text: "Parle-G Gold / Net Wt: 100 g / MRP ₹ 30.00 incl. of all taxes" },
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "COMPLIANT",
          detected_value: "MRP ₹ 30.00 incl. of all taxes",
          normalized_value: "MRP=30.00; currency=₹; tax_inclusive=true",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "MRP declaration conforms to Rule 2(m) format with Rupee symbol and tax-inclusive suffix.",
          explanation_for_inspector: "MRP declaration complies with Rule 2(m). It is formatted using the Rupee symbol and includes the mandatory tax declaration.",
          evidence: { raw_ocr_text: "MRP ₹ 30.00 incl. of all taxes", bounding_box: { x: 60, y: 130, w: 250, h: 30 } },
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-03",
          status: "COMPLIANT",
          detected_value: "100 g",
          normalized_value: "magnitude=100.0; unit=g",
          detection_confidence: 0.97,
          applicability_confidence: 1.0,
          reason: "Metric unit symbol 'g' matches International System of Units under Rule 13(5).",
          explanation_for_inspector: "The quantity unit symbol complies with Rule 13.",
          evidence: { raw_ocr_text: "Net Weight: 100 g", bounding_box: { x: 80, y: 280, w: 160, h: 40 } },
          rule_version: RULE_METADATA["REQ-MVP-03"],
        },
        {
          rule_id: "REQ-MVP-04",
          status: "COMPLIANT",
          detected_value: "100 g",
          normalized_value: "magnitude=100.0; boundary=valid_sub_kg",
          detection_confidence: 0.97,
          applicability_confidence: 1.0,
          reason: "Quantity less than 1 kg is correctly expressed in grams under Rule 13(2)(a).",
          explanation_for_inspector: "Quantity expression scale matches boundary thresholds under Rule 13.",
          evidence: { raw_ocr_text: "100 g" },
          rule_version: RULE_METADATA["REQ-MVP-04"],
        },
        {
          rule_id: "REQ-MVP-05",
          status: "COMPLIANT",
          detected_value: "Net Weight: 100 g",
          normalized_value: "prohibited_qualifiers=none",
          detection_confidence: 0.97,
          applicability_confidence: 1.0,
          reason: "No illegal qualitative words (e.g. 'approx', 'min') detected on the quantity line.",
          explanation_for_inspector: "The quantity declaration contains no illegal qualitative qualifiers.",
          evidence: { raw_ocr_text: "Net Weight: 100 g" },
          rule_version: RULE_METADATA["REQ-MVP-05"],
        },
        {
          rule_id: "REQ-MVP-06",
          status: "COMPLIANT",
          detected_value: "08/2026",
          normalized_value: "month=08; year=2026; overwriting=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Valid month and year structure detected. No character stroke overwriting found.",
          explanation_for_inspector: "Date of manufacture is clearly printed in a valid format.",
          evidence: { raw_ocr_text: "Mfg Date: 08/2026" },
          rule_version: RULE_METADATA["REQ-MVP-06"],
        },
        {
          rule_id: "REQ-MVP-07",
          status: "COMPLIANT",
          detected_value: "1800227788 | care@parle.biz",
          normalized_value: "phone=1800227788; email=care@parle.biz; address=present",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "Mandatory telephone helpline and grievance email identified under Rule 6(2).",
          explanation_for_inspector: "Consumer care contact details are complete under Rule 6(2).",
          evidence: { raw_ocr_text: "Toll Free: 1800227788, Email: care@parle.biz" },
          rule_version: RULE_METADATA["REQ-MVP-07"],
        },
        {
          rule_id: "REQ-MVP-08",
          status: "COMPLIANT",
          detected_value: "Vile Parle East, Mumbai, Maharashtra - 400057",
          normalized_value: "premises=North Level Factory Unit 4; city=Mumbai; state=Maharashtra; pin=400057",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "Complete factory address with street indices and valid 6-digit PIN code detected.",
          explanation_for_inspector: "Address block contains complete postal details including street indices and PIN code.",
          evidence: { raw_ocr_text: "Parle Products Pvt. Ltd., Mumbai, Maharashtra - 400057" },
          rule_version: RULE_METADATA["REQ-MVP-08"],
        },
        {
          rule_id: "REQ-MVP-09",
          status: "NOT_APPLICABLE",
          detected_value: "India",
          normalized_value: "country_of_origin=India; imported=false",
          detection_confidence: 0.99,
          applicability_confidence: 1.0,
          reason: "Domestic Indian origin confirmed. Rule 10(1) Proviso 2 (foreign importer PDP) does not apply.",
          explanation_for_inspector: "Product is manufactured domestically in India; foreign importer rules are not applicable.",
          evidence: { raw_ocr_text: "Country of Origin: India" },
          rule_version: RULE_METADATA["REQ-MVP-09"],
        },
        {
          rule_id: "REQ-MVP-10",
          status: "NOT_APPLICABLE",
          detected_value: "Biscuits",
          normalized_value: "category=Biscuits",
          detection_confidence: 0.99,
          applicability_confidence: 1.0,
          reason: "Commodity classified as Biscuits, not Pan Masala.",
          explanation_for_inspector: "Product is not Pan Masala. G.S.R. 881(E) router inactive.",
          evidence: { raw_ocr_text: "Glucose Biscuits" },
          rule_version: RULE_METADATA["REQ-MVP-10"],
        },
        {
          rule_id: "REQ-MVP-11",
          status: "NOT_APPLICABLE",
          detected_value: "Biscuits",
          normalized_value: "medical_device=false",
          detection_confidence: 0.99,
          applicability_confidence: 1.0,
          reason: "No medical device registration or CDSCO markers found.",
          explanation_for_inspector: "Product is not a medical device. Standard PCR 2011 checks apply.",
          evidence: { raw_ocr_text: "Parle-G Gold Glucose Biscuits" },
          rule_version: RULE_METADATA["REQ-MVP-11"],
        },
        {
          rule_id: "REQ-MVP-12",
          status: "COMPLIANT",
          detected_value: "100 g",
          normalized_value: "category=Biscuits; size=100g; standard_size=true",
          detection_confidence: 0.97,
          applicability_confidence: 1.0,
          reason: "100g is a prescribed standard pack size for Biscuits under the Second Schedule.",
          explanation_for_inspector: "The package is in a prescribed standard size under the Second Schedule.",
          evidence: { raw_ocr_text: "100 g" },
          rule_version: RULE_METADATA["REQ-MVP-12"],
        },
        {
          rule_id: "REQ-MVP-13",
          status: "COMPLIANT",
          detected_value: "Directly printed packaging",
          normalized_value: "stickers_found=0",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "No individual correction stickers or paper overlays detected on declarations.",
          explanation_for_inspector: "No non-compliant stickers detected on the package.",
          evidence: { raw_ocr_text: "Printed carton packaging" },
          rule_version: RULE_METADATA["REQ-MVP-13"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Numeral height = 4.2mm (est.)",
          normalized_value: "quiet_zone_simulated=1Hx2H",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Assistive Visual Aid: 1H vertical and 2H horizontal clearance box rendered for inspector visual verification.",
          explanation_for_inspector: "A clearance box (1H vertical clearance, 2H horizontal clearance) has been drawn around the net quantity. Please physically verify that this area is completely free of other printed logos, graphics, or text.",
          evidence: { raw_ocr_text: "100 g", bounding_box: { x: 80, y: 280, w: 160, h: 40 } },
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Contrast ratio = 7.4:1 (estimated)",
          normalized_value: "legibility=apparent_high",
          detection_confidence: 0.89,
          applicability_confidence: 1.0,
          reason: "Assistive Visual Aid: Rule 9(1) contrast is qualitative in statute. Requires inspector confirmation.",
          explanation_for_inspector: "Price and quantity numerals appear conspicuously contrasted against the background. Confirm physical prominence under natural lighting.",
          evidence: { raw_ocr_text: "MRP ₹ 30.00 / Net Wt: 100 g" },
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 2. PRODUCT WITH POTENTIAL VIOLATIONS (Missing Date & Missing Consumer Care)
  // ---------------------------------------------------------------------------
  "insp-002": {
    inspection: {
      id: "insp-002",
      created_at: "2026-09-06T11:00:00Z",
      updated_at: "2026-09-06T11:02:15Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "POTENTIAL_VIOLATION",
      product_name: "Himalayan Berry Preserve",
      brand_name: "Orchard Fresh",
      commodity_category: "Preserved Fruit",
      inspector_id: "insp_mumbai_04",
      image_coverage: { front: true, back: true, side: true, top: false },
      notes: "Seized sample from wholesale distributor. No date code found on back label.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-002-f",
        inspection_id: "insp-002",
        file_name: "berry_jam_front.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 420000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fee2e2'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23fef2f2' stroke='%23dc2626' stroke-width='2'/><text x='300' y='100' font-family='sans-serif' font-size='24' font-weight='bold' fill='%23991b1b' text-anchor='middle'>Orchard Fresh Himalayan Berry Jam</text><text x='300' y='140' font-family='sans-serif' font-size='16' fill='%23b91c1c' text-anchor='middle'>Net Qty: 500 g</text></svg>",
        uploaded_at: "2026-09-06T11:00:10Z",
      },
      {
        evidence_id: "ev-002-b",
        inspection_id: "insp-002",
        file_name: "berry_jam_back.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 380000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23f8fafc'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23cbd5e1' stroke-width='2'/><text x='60' y='80' font-family='sans-serif' font-size='14' fill='%23334155'>Packed by: Orchard Foods, Solan, HP 173212</text><text x='60' y='130' font-family='sans-serif' font-size='16' font-weight='bold' fill='%230f172a'>MRP ₹ 195.00 inclusive of all taxes</text><text x='60' y='200' font-family='sans-serif' font-size='14' fill='%23dc2626'>[ALERT: Date of Mfg block completely absent]</text><text x='60' y='240' font-family='sans-serif' font-size='14' fill='%23dc2626'>[ALERT: Consumer care phone/email missing]</text></svg>",
        uploaded_at: "2026-09-06T11:00:20Z",
      },
    ],
    extraction: {
      inspection_id: "insp-002",
      product_name: {
        value: "Berry Preserve",
        raw_text: "Orchard Fresh Himalayan Berry Jam",
        confidence: 0.92,
        location: "front",
      },
      commodity_category: {
        value: "Preserved Fruit",
        raw_text: "Fruit Preserve",
        confidence: 0.90,
        location: "front",
      },
      manufacturer: {
        premises: "Shed 12",
        street: "Old Shimla Highway",
        city: "Solan",
        state: "Himachal Pradesh",
        pin_code: "173212",
        raw_text: "Packed by: Orchard Foods, Shed 12, Old Shimla Highway, Solan, HP - 173212",
        confidence: 0.91,
      },
      country_of_origin: {
        value: "India",
        raw_text: "Made in India",
        confidence: 0.95,
      },
      net_quantity: {
        value: 500.0,
        unit: "g",
        raw_text: "Net Weight: 500 g",
        confidence: 0.94,
        location: "front",
      },
      mrp: {
        value: 195.0,
        currency: "₹",
        tax_inclusivity: true,
        raw_text: "MRP ₹ 195.00 inclusive of all taxes",
        confidence: 0.9,
        location: "back",
      },
      date_of_manufacture: null, // MISSING
      consumer_care: null, // MISSING
      image_coverage: { front: true, back: true, side: true, top: false },
    },
    compliance: {
      inspection_id: "insp-002",
      overall_status: "POTENTIAL_VIOLATION",
      summary_counts: {
        total_rules: 15,
        compliant: 8,
        potential_violations: 3,
        needs_manual_review: 3,
        not_applicable: 1,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T11:02:15Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-01",
          status: "POTENTIAL_VIOLATION",
          detected_value: "Date and Consumer Care absent on submitted panels",
          normalized_value: "missing_blocks=[date, consumer_care]",
          detection_confidence: 0.92,
          applicability_confidence: 1.0,
          reason: "Mandatory declarations under Rule 6(1) are missing despite front, back, and side panel coverage.",
          explanation_for_inspector: "The package lacks mandatory statutory declarations (Date of Manufacture and Consumer Care). Rule 6(1) requires these on all retail packaged goods.",
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "COMPLIANT",
          detected_value: "MRP ₹ 195.00 inclusive of all taxes",
          normalized_value: "MRP=195.00; tax_inclusive=true",
          detection_confidence: 0.9,
          applicability_confidence: 1.0,
          reason: "MRP format matches Rule 2(m) with rupee symbol and tax inclusion.",
          explanation_for_inspector: "MRP declaration complies with Rule 2(m).",
          evidence: { raw_ocr_text: "MRP ₹ 195.00 inclusive of all taxes" },
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-03",
          status: "COMPLIANT",
          detected_value: "500 g",
          normalized_value: "magnitude=500.0; unit=g",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "Unit symbol 'g' is valid SI metric symbol.",
          explanation_for_inspector: "Quantity unit complies with Rule 13.",
          rule_version: RULE_METADATA["REQ-MVP-03"],
        },
        {
          rule_id: "REQ-MVP-04",
          status: "COMPLIANT",
          detected_value: "500 g",
          normalized_value: "scale=grams",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "Sub-1kg correctly expressed in grams.",
          explanation_for_inspector: "Scale transition boundary complies with Rule 13(2).",
          rule_version: RULE_METADATA["REQ-MVP-04"],
        },
        {
          rule_id: "REQ-MVP-05",
          status: "COMPLIANT",
          detected_value: "Net Weight: 500 g",
          normalized_value: "qualifiers=none",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "No illegal qualifiers detected.",
          explanation_for_inspector: "No prohibited quantity qualifiers found.",
          rule_version: RULE_METADATA["REQ-MVP-05"],
        },
        {
          rule_id: "REQ-MVP-06",
          status: "POTENTIAL_VIOLATION",
          detected_value: "NONE",
          normalized_value: "date_declaration=missing",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Month and year of manufacture or packing is completely absent from all submitted surfaces.",
          explanation_for_inspector: "No date of manufacture or packing found. Rule 6(1)(d) strictly mandates declaring the month and year of pre-packing.",
          evidence: { raw_ocr_text: "[No date block found]" },
          rule_version: RULE_METADATA["REQ-MVP-06"],
        },
        {
          rule_id: "REQ-MVP-07",
          status: "POTENTIAL_VIOLATION",
          detected_value: "NONE",
          normalized_value: "consumer_care=missing",
          detection_confidence: 0.93,
          applicability_confidence: 1.0,
          reason: "Consumer care grievance block is absent. No telephone helpline or email provided.",
          explanation_for_inspector: "Missing mandatory consumer care fields under Rule 6(2). Every package must carry telephone and email grievance contact details.",
          evidence: { raw_ocr_text: "[No consumer care block]" },
          rule_version: RULE_METADATA["REQ-MVP-07"],
        },
        {
          rule_id: "REQ-MVP-08",
          status: "COMPLIANT",
          detected_value: "Shed 12, Old Shimla Highway, Solan, HP - 173212",
          normalized_value: "premises=Shed 12; pin=173212",
          detection_confidence: 0.91,
          applicability_confidence: 1.0,
          reason: "Complete physical address with premises and PIN code.",
          explanation_for_inspector: "Address block complies with Rule 10(1) Explanation.",
          rule_version: RULE_METADATA["REQ-MVP-08"],
        },
        {
          rule_id: "REQ-MVP-09",
          status: "NOT_APPLICABLE",
          detected_value: "India",
          normalized_value: "origin=India",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Domestic product.",
          explanation_for_inspector: "Not applicable for domestic goods.",
          rule_version: RULE_METADATA["REQ-MVP-09"],
        },
        {
          rule_id: "REQ-MVP-10",
          status: "COMPLIANT",
          detected_value: "Preserved Fruit",
          normalized_value: "is_pan_masala=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Standard retail goods checks apply.",
          explanation_for_inspector: "Category verified.",
          rule_version: RULE_METADATA["REQ-MVP-10"],
        },
        {
          rule_id: "REQ-MVP-11",
          status: "COMPLIANT",
          detected_value: "Preserved Fruit",
          normalized_value: "is_medical_device=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Non-medical item.",
          explanation_for_inspector: "Standard PCR checks apply.",
          rule_version: RULE_METADATA["REQ-MVP-11"],
        },
        {
          rule_id: "REQ-MVP-12",
          status: "COMPLIANT",
          detected_value: "500 g",
          normalized_value: "category=Jam; standard=true",
          detection_confidence: 0.9,
          applicability_confidence: 1.0,
          reason: "Prescribed size under Second Schedule.",
          explanation_for_inspector: "Pack size complies.",
          rule_version: RULE_METADATA["REQ-MVP-12"],
        },
        {
          rule_id: "REQ-MVP-13",
          status: "COMPLIANT",
          detected_value: "No stickers",
          normalized_value: "stickers=0",
          detection_confidence: 0.92,
          applicability_confidence: 1.0,
          reason: "No non-compliant alteration stickers.",
          explanation_for_inspector: "No stickers detected.",
          rule_version: RULE_METADATA["REQ-MVP-13"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Quiet Zone simulated",
          normalized_value: "aid_only=true",
          detection_confidence: 0.85,
          applicability_confidence: 1.0,
          reason: "Assistive visual aid.",
          explanation_for_inspector: "Verify quiet zone clearance around 500g numeral.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Contrast ratio = 6.8:1",
          normalized_value: "aid_only=true",
          detection_confidence: 0.86,
          applicability_confidence: 1.0,
          reason: "Assistive visual aid.",
          explanation_for_inspector: "Verify contrast on jar label.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 3. PRODUCT REQUIRING MANUAL REVIEW (Low OCR confidence on MRP tax phrase — Fix 1)
  // ---------------------------------------------------------------------------
  "insp-003": {
    inspection: {
      id: "insp-003",
      created_at: "2026-09-06T11:30:00Z",
      updated_at: "2026-09-06T11:31:20Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "NEEDS_MANUAL_REVIEW",
      product_name: "Masala Chai Premium Blend",
      brand_name: "Tea Leaf Co",
      commodity_category: "Tea",
      inspector_id: "insp_kolkata_02",
      image_coverage: { front: true, back: true, side: false, top: false },
      notes: "Reflection on cellophane wrap reduced OCR confidence near price block.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-003-b",
        inspection_id: "insp-003",
        file_name: "tea_back_crop.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 280000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fef3c7'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23fffbeb' stroke='%23d97706' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='20' font-weight='bold' fill='%2378350f' text-anchor='middle'>Tea Leaf Co Masala Chai</text><text x='300' y='140' font-family='sans-serif' font-size='15' fill='%2392400e' text-anchor='middle'>Net Wt: 250 g</text><rect x='150' y='200' width='300' height='60' fill='%23fed7aa' stroke='%23ea580c' stroke-dasharray='4'/><text x='300' y='235' font-family='sans-serif' font-size='14' fill='%239a3412' text-anchor='middle'>MRP ₹ 140 [incl of taxes - partially blurred]</text></svg>",
        uploaded_at: "2026-09-06T11:30:15Z",
      },
    ],
    extraction: {
      inspection_id: "insp-003",
      product_name: { value: "Masala Chai", raw_text: "Masala Chai Premium", confidence: 0.91 },
      commodity_category: { value: "Tea", raw_text: "Tea", confidence: 0.95 },
      net_quantity: { value: 250.0, unit: "g", raw_text: "Net Qty: 250 g", confidence: 0.93 },
      mrp: {
        value: 140.0,
        currency: "₹",
        tax_inclusivity: true,
        raw_text: "MRP ₹ 140 incl of taxes",
        confidence: 0.62, // Low confidence!
        location: "back",
      },
      date_of_manufacture: { month: "08", year: "2026", raw_text: "08/2026", confidence: 0.92 },
      image_coverage: { front: true, back: true, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-003",
      overall_status: "NEEDS_MANUAL_REVIEW",
      summary_counts: {
        total_rules: 15,
        compliant: 10,
        potential_violations: 0,
        needs_manual_review: 4,
        not_applicable: 1,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T11:31:20Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-02",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "MRP ₹ 140 incl of taxes",
          normalized_value: "MRP=140.0; tax_inclusive=uncertain",
          detection_confidence: 0.62,
          applicability_confidence: 1.0,
          reason: "Tax-inclusivity phrase detected but OCR confidence (0.62) is below the 0.75 threshold (Fix 1).",
          explanation_for_inspector: "Price and tax-inclusion phrase were found, but confidence is low due to image glare. Please confirm manually before accepting.",
          evidence: { raw_ocr_text: "MRP ₹ 140 incl of taxes", bounding_box: { x: 150, y: 200, w: 300, h: 60 } },
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-01",
          status: "COMPLIANT",
          detected_value: "All 5 core blocks present",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Mandatory declarations present.",
          explanation_for_inspector: "Core declarations detected.",
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Simulated 1Hx2H box",
          detection_confidence: 0.85,
          applicability_confidence: 1.0,
          reason: "Assistive visual aid.",
          explanation_for_inspector: "Check quiet zone around 250g.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Glossy reflection detected",
          detection_confidence: 0.7,
          applicability_confidence: 1.0,
          reason: "Assistive visual aid.",
          explanation_for_inspector: "Glare might impair in-person legibility.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 4. PRODUCT WITH MRP CONFLICT (Front ₹190 vs Back ₹210)
  // ---------------------------------------------------------------------------
  "insp-004": {
    inspection: {
      id: "insp-004",
      created_at: "2026-09-06T12:00:00Z",
      updated_at: "2026-09-06T12:01:45Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "NEEDS_MANUAL_REVIEW",
      product_name: "Royal Heritage Basmati Rice 1kg",
      brand_name: "Royal Heritage",
      commodity_category: "Rice",
      inspector_id: "insp_chandigarh_02",
      image_coverage: { front: true, back: true, side: true, top: false },
      notes: "Front promotional flash lists ₹190; back statutory stamp lists ₹210.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-004-f",
        inspection_id: "insp-004",
        file_name: "rice_front_mrp.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 350000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23ecfdf5'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23059669' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='22' font-weight='bold' fill='%23065f46' text-anchor='middle'>Royal Heritage Basmati Rice</text><rect x='200' y='180' width='200' height='60' fill='%23dcfce7' stroke='%2316a34a'/><text x='300' y='218' font-family='sans-serif' font-size='20' font-weight='bold' fill='%2315803d' text-anchor='middle'>Special Price ₹ 190</text></svg>",
        uploaded_at: "2026-09-06T12:00:10Z",
      },
      {
        evidence_id: "ev-004-b",
        inspection_id: "insp-004",
        file_name: "rice_back_mrp.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 360000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fff7ed'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23ea580c' stroke-width='2'/><text x='60' y='80' font-family='sans-serif' font-size='16' font-weight='bold' fill='%239a3412'>Statutory Declarations Panel (Back)</text><rect x='60' y='150' width='320' height='50' fill='%23ffedd5' stroke='%23c2410c'/><text x='70' y='182' font-family='sans-serif' font-size='16' font-weight='bold' fill='%237c2d12'>MRP ₹ 210.00 incl. of all taxes</text></svg>",
        uploaded_at: "2026-09-06T12:00:20Z",
      },
    ],
    extraction: {
      inspection_id: "insp-004",
      product_name: { value: "Basmati Rice", raw_text: "Royal Heritage Basmati Rice", confidence: 0.96 },
      commodity_category: { value: "Rice", raw_text: "Rice", confidence: 0.97 },
      net_quantity: { value: 1.0, unit: "kg", raw_text: "Net Weight: 1 kg", confidence: 0.96 },
      mrp: {
        value: 210.0,
        currency: "₹",
        tax_inclusivity: true,
        raw_text: "MRP ₹ 210.00 incl. of all taxes",
        confidence: 0.95,
        location: "back",
      },
      mrp_observations: [
        {
          value: 190.0,
          currency: "₹",
          tax_inclusivity: true,
          raw_text: "Special Price ₹ 190",
          confidence: 0.92,
          location: "front",
          image_id: "ev-004-f",
        },
        {
          value: 210.0,
          currency: "₹",
          tax_inclusivity: true,
          raw_text: "MRP ₹ 210.00 incl. of all taxes",
          confidence: 0.95,
          location: "back",
          image_id: "ev-004-b",
        },
      ],
      date_of_manufacture: { month: "08", year: "2026", raw_text: "08/2026", confidence: 0.94 },
      image_coverage: { front: true, back: true, side: true, top: false },
    },
    compliance: {
      inspection_id: "insp-004",
      overall_status: "NEEDS_MANUAL_REVIEW",
      summary_counts: {
        total_rules: 15,
        compliant: 10,
        potential_violations: 0,
        needs_manual_review: 3,
        not_applicable: 2,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T12:01:45Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-02",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Front: ₹ 190 vs Back: ₹ 210.00",
          normalized_value: "conflict_detected=[190.00, 210.00]",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "Conflicting MRP declarations found across submitted surfaces. System never auto-resolves price conflicts.",
          explanation_for_inspector: "Multi-surface MRP discrepancy detected: Front displays ₹190 while Back displays ₹210. Under Legal Metrology regulations, two conflicting retail prices cannot be declared.",
          evidence: { raw_ocr_text: "Front: 'Special Price ₹ 190' | Back: 'MRP ₹ 210.00 incl. of all taxes'" },
          conflicts: {
            field: "mrp",
            values_found: [
              { value: "₹ 190.00", image_id: "ev-004-f", location: "front", confidence: 0.92, raw_text: "Special Price ₹ 190" },
              { value: "₹ 210.00", image_id: "ev-004-b", location: "back", confidence: 0.95, raw_text: "MRP ₹ 210.00 incl. of all taxes" },
            ],
            resolution: "NEEDS_MANUAL_REVIEW",
            reason: "Conflicting MRP values detected across submitted package surfaces (Section 6).",
          },
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-03",
          status: "COMPLIANT",
          detected_value: "1 kg",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "Unit kg valid under Rule 13.",
          explanation_for_inspector: "Valid SI unit symbol.",
          rule_version: RULE_METADATA["REQ-MVP-03"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "1Hx2H clearance simulated",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Quiet zone visual check.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "High contrast",
          detection_confidence: 0.9,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Confirm prominence under natural light.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 5. PRODUCT WITH NET QUANTITY CONFLICT (Front 500g vs Back 450g)
  // ---------------------------------------------------------------------------
  "insp-005": {
    inspection: {
      id: "insp-005",
      created_at: "2026-09-06T12:30:00Z",
      updated_at: "2026-09-06T12:31:30Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "NEEDS_MANUAL_REVIEW",
      product_name: "Nature Pure Organic Cashews",
      brand_name: "Nature Pure",
      commodity_category: "Dry Fruits",
      inspector_id: "insp_bengaluru_01",
      image_coverage: { front: true, back: true, side: true, top: true },
      notes: "Front carton states 500g, back technical specifications block states 450g.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-005-f",
        inspection_id: "insp-005",
        file_name: "cashews_front.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 320000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fefce8'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23ca8a04' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='22' font-weight='bold' fill='%23854d0e' text-anchor='middle'>Organic Cashews</text><rect x='200' y='180' width='200' height='50' fill='%23fef08a' stroke='%23eab308'/><text x='300' y='212' font-family='sans-serif' font-size='18' font-weight='bold' fill='%23713f12' text-anchor='middle'>Net Qty: 500 g</text></svg>",
        uploaded_at: "2026-09-06T12:30:10Z",
      },
      {
        evidence_id: "ev-005-b",
        inspection_id: "insp-005",
        file_name: "cashews_back.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 310000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fffbeb'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23b45309' stroke-width='2'/><text x='60' y='80' font-family='sans-serif' font-size='16' font-weight='bold' fill='%2378350f'>Product Specifications</text><rect x='60' y='140' width='250' height='45' fill='%23fef3c7' stroke='%23d97706'/><text x='70' y='170' font-family='sans-serif' font-size='16' font-weight='bold' fill='%2392400e'>Weight: 450 g</text></svg>",
        uploaded_at: "2026-09-06T12:30:20Z",
      },
    ],
    extraction: {
      inspection_id: "insp-005",
      product_name: { value: "Organic Cashews", raw_text: "Nature Pure Organic Cashews", confidence: 0.95 },
      commodity_category: { value: "Dry Fruits", raw_text: "Dry Fruits", confidence: 0.96 },
      net_quantity: {
        value: 500.0,
        unit: "g",
        raw_text: "Net Qty: 500 g",
        confidence: 0.95,
        location: "front",
      },
      net_quantity_observations: [
        {
          value: 500.0,
          unit: "g",
          raw_text: "Net Qty: 500 g",
          confidence: 0.95,
          location: "front",
          image_id: "ev-005-f",
        },
        {
          value: 450.0,
          unit: "g",
          raw_text: "Weight: 450 g",
          confidence: 0.93,
          location: "back",
          image_id: "ev-005-b",
        },
      ],
      mrp: { value: 450.0, currency: "₹", tax_inclusivity: true, raw_text: "MRP ₹ 450.00 incl. of all taxes", confidence: 0.94 },
      date_of_manufacture: { month: "07", year: "2026", raw_text: "07/2026", confidence: 0.91 },
      image_coverage: { front: true, back: true, side: true, top: true },
    },
    compliance: {
      inspection_id: "insp-005",
      overall_status: "NEEDS_MANUAL_REVIEW",
      summary_counts: {
        total_rules: 15,
        compliant: 10,
        potential_violations: 0,
        needs_manual_review: 3,
        not_applicable: 2,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T12:31:30Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-03",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Front: 500 g vs Back: 450 g",
          normalized_value: "qty_conflict=[500.0, 450.0]",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "Conflicting net quantity values detected between front and back surfaces. Preserving all observations without automatic override.",
          explanation_for_inspector: "Multi-surface Net Quantity conflict detected: Front indicates 500 g, while Back indicates 450 g. Requires physical verification of actual container contents.",
          evidence: { raw_ocr_text: "Front: 'Net Qty: 500 g' | Back: 'Weight: 450 g'" },
          conflicts: {
            field: "net_quantity",
            values_found: [
              { value: "500 g", image_id: "ev-005-f", location: "front", confidence: 0.95, raw_text: "Net Qty: 500 g" },
              { value: "450 g", image_id: "ev-005-b", location: "back", confidence: 0.93, raw_text: "Weight: 450 g" },
            ],
            resolution: "NEEDS_MANUAL_REVIEW",
            reason: "Conflicting Net Quantity values detected across package surfaces (Section 6).",
          },
          rule_version: RULE_METADATA["REQ-MVP-03"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "COMPLIANT",
          detected_value: "MRP ₹ 450.00 incl. of all taxes",
          detection_confidence: 0.94,
          applicability_confidence: 1.0,
          reason: "MRP format compliant.",
          explanation_for_inspector: "MRP complies with Rule 2(m).",
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "1Hx2H visual aid",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Quiet zone visual aid.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Visual aid contrast",
          detection_confidence: 0.87,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Contrast check required.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 6. MEDICAL DEVICE CONFIRMATION PENDING (Fix 2)
  // ---------------------------------------------------------------------------
  "insp-006": {
    inspection: {
      id: "insp-006",
      created_at: "2026-09-06T13:00:00Z",
      updated_at: "2026-09-06T13:01:20Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "NEEDS_MANUAL_REVIEW",
      product_name: "MediClean Sterile Gauze Swab",
      brand_name: "MediClean",
      commodity_category: "Medical Device",
      inspector_id: "insp_ahmedabad_01",
      image_coverage: { front: true, back: true, side: false, top: false },
      notes: "License text shows 'Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)'. Confirmation gate active.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-006-b",
        inspection_id: "insp-006",
        file_name: "mediclean_back.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 340000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23f0fdfa'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%230d9488' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='20' font-weight='bold' fill='%23115e59' text-anchor='middle'>MediClean Surgical Ltd</text><rect x='80' y='140' width='440' height='60' fill='%23ccfbf1' stroke='%230f766e'/><text x='300' y='175' font-family='sans-serif' font-size='15' font-weight='bold' fill='%23134e4a' text-anchor='middle'>Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)</text></svg>",
        uploaded_at: "2026-09-06T13:00:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-006",
      product_name: { value: "Sterile Gauze Swab", raw_text: "MediClean Sterile Gauze Swab 10cm x 10cm", confidence: 0.96 },
      commodity_category: { value: "Medical Device", raw_text: "Medical Device", confidence: 0.98 },
      medical_device_markers: { value: "MD-1402", raw_text: "Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)", confidence: 0.96, location: "back" },
      manufacturer: { premises: "Plot 88 GIDC", street: "Vatva", city: "Ahmedabad", state: "Gujarat", pin_code: "382445", raw_text: "MediClean Surgical Ltd, Ahmedabad 382445", confidence: 0.94 },
      net_quantity: { value: 10.0, unit: "N", raw_text: "Quantity: 10 N", confidence: 0.95 },
      mrp: { value: 150.0, currency: "₹", tax_inclusivity: true, raw_text: "MRP ₹ 150.00 incl. of all taxes", confidence: 0.93 },
      date_of_manufacture: { month: "06", year: "2026", raw_text: "06/2026", confidence: 0.92 },
      image_coverage: { front: true, back: true, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-006",
      overall_status: "NEEDS_MANUAL_REVIEW",
      summary_counts: {
        total_rules: 15,
        compliant: 10,
        potential_violations: 0,
        needs_manual_review: 3,
        not_applicable: 2,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T13:01:20Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-11",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)",
          normalized_value: "probable_medical_device=true; confirmation_required=true",
          detection_confidence: 0.96,
          applicability_confidence: 0.92,
          reason: "Probable medical device license marker detected. Fix 2 requires explicit inspector confirmation before switching rule sets.",
          explanation_for_inspector: "Probable medical device detected on label (MD-1402). Legal Metrology provisos state that Medical Devices Rules, 2017 apply instead of standard PCR 2011. Confirm classification to switch rule sets.",
          evidence: { raw_ocr_text: "Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)" },
          rule_version: RULE_METADATA["REQ-MVP-11"],
        },
        {
          rule_id: "REQ-MVP-01",
          status: "COMPLIANT",
          detected_value: "Mandatory blocks present",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Declarations detected pending medical device switch.",
          explanation_for_inspector: "Declarations present under standard PCR rules.",
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Visual aid only",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Check quiet zone.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Visual aid only",
          detection_confidence: 0.89,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Check contrast.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 7. CONFIRMED MEDICAL DEVICE (PCR rules suppressed to NOT_APPLICABLE)
  // ---------------------------------------------------------------------------
  "insp-007": {
    inspection: {
      id: "insp-007",
      created_at: "2026-09-06T13:15:00Z",
      updated_at: "2026-09-06T13:16:45Z",
      status: "REPORT_GENERATED",
      compliance_status: "NOT_APPLICABLE",
      product_name: "MediClean Sterile Gauze Swab (Confirmed)",
      brand_name: "MediClean",
      commodity_category: "Medical Device",
      inspector_id: "insp_ahmedabad_01",
      image_coverage: { front: true, back: true, side: false, top: false },
      notes: "Inspector confirmed Medical Device classification under Rule 2(h) Proviso. Standard PCR rules suppressed.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-007-b",
        inspection_id: "insp-007",
        file_name: "mediclean_back.jpg",
        image_type: "back",
        mime_type: "image/jpeg",
        file_size_bytes: 340000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23f1f5f9'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23475569' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='20' font-weight='bold' fill='%23334155' text-anchor='middle'>CDSCO Medical Device Confirmation</text><text x='300' y='140' font-family='sans-serif' font-size='16' fill='%23475569' text-anchor='middle'>PCR 2011 Checks Suppressed -> Routed to MDR 2017</text></svg>",
        uploaded_at: "2026-09-06T13:15:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-007",
      product_name: { value: "Sterile Gauze Swab", raw_text: "MediClean Sterile Gauze Swab", confidence: 0.96 },
      commodity_category: { value: "Medical Device", raw_text: "Medical Device", confidence: 0.98 },
      medical_device_markers: { value: "MD-1402", raw_text: "Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)", confidence: 0.96 },
      image_coverage: { front: true, back: true, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-007",
      overall_status: "NOT_APPLICABLE",
      summary_counts: {
        total_rules: 15,
        compliant: 0,
        potential_violations: 0,
        needs_manual_review: 0,
        not_applicable: 15, // All PCR rules bypassed!
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T13:16:45Z",
      engine_version: "v2.0.0-verified",
      rule_results: Object.keys(RULE_METADATA).map((rId) => ({
        rule_id: rId,
        status: "NOT_APPLICABLE",
        detected_value: rId === "REQ-MVP-11" ? "MD-1402 Confirmed by Inspector" : "Bypassed",
        normalized_value: "routed_to=Medical_Devices_Rules_2017",
        detection_confidence: 0.98,
        applicability_confidence: 1.0,
        reason: "Medical Device confirmed by inspector under Rule 2(h)/7(2)/7(3) provisos. Standard PCR 2011 checks bypassed.",
        explanation_for_inspector: "Inspector explicitly confirmed medical device status. Standard Legal Metrology checks suppressed and routed to Medical Devices Rules, 2017.",
        evidence: { raw_ocr_text: "Mfg. Lic. No. MD-1402 (CDSCO Reg. MDR-2017)" },
        rule_version: RULE_METADATA[rId],
      })),
    },
  },

  // ---------------------------------------------------------------------------
  // 8. NOT_DETECTED FIELDS (Incomplete surface coverage prompt)
  // ---------------------------------------------------------------------------
  "insp-008": {
    inspection: {
      id: "insp-008",
      created_at: "2026-09-06T14:00:00Z",
      updated_at: "2026-09-06T14:01:10Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "NEEDS_MANUAL_REVIEW",
      product_name: "Gourmet Kitchen Garam Masala",
      brand_name: "Gourmet Kitchen",
      commodity_category: "Spices",
      inspector_id: "insp_delhi_03",
      image_coverage: { front: true, back: false, side: false, top: false }, // Only Front uploaded!
      notes: "Inspector only uploaded front image of carton. Missing back face.",
      images_count: 1,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-008-f",
        inspection_id: "insp-008",
        file_name: "garam_masala_front.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 290000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fff7ed'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23f97316' stroke-width='2'/><text x='300' y='90' font-family='sans-serif' font-size='24' font-weight='bold' fill='%23c2410c' text-anchor='middle'>Gourmet Kitchen Garam Masala</text><text x='300' y='140' font-family='sans-serif' font-size='16' fill='%23ea580c' text-anchor='middle'>Net Qty: 100 g</text><rect x='100' y='220' width='400' height='60' fill='%23ffedd5' stroke='%23f97316'/><text x='300' y='255' font-family='sans-serif' font-size='14' fill='%239a3412' text-anchor='middle'>[Front Panel Only — Back & Side Panels Not Submitted]</text></svg>",
        uploaded_at: "2026-09-06T14:00:05Z",
      },
    ],
    extraction: {
      inspection_id: "insp-008",
      product_name: { value: "Garam Masala", raw_text: "Gourmet Kitchen Garam Masala", confidence: 0.95 },
      commodity_category: { value: "Spices", raw_text: "Spices", confidence: 0.94 },
      net_quantity: { value: 100.0, unit: "g", raw_text: "Net Qty: 100 g", confidence: 0.96, location: "front" },
      mrp: null, // NOT FOUND ON FRONT
      date_of_manufacture: null, // NOT FOUND ON FRONT
      manufacturer: null, // NOT FOUND ON FRONT
      consumer_care: null, // NOT FOUND ON FRONT
      image_coverage: { front: true, back: false, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-008",
      overall_status: "NEEDS_MANUAL_REVIEW",
      summary_counts: {
        total_rules: 15,
        compliant: 3,
        potential_violations: 0,
        needs_manual_review: 4,
        not_applicable: 2,
        not_detected: 6, // Crucial: NOT_DETECTED, NEVER turned into POTENTIAL_VIOLATION!
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T14:01:10Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-01",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Front face only submitted",
          normalized_value: "coverage_incomplete=true",
          detection_confidence: 0.9,
          applicability_confidence: 1.0,
          reason: "Submitted packaging surfaces do not cover all mandatory faces. Prompting inspector for additional surfaces.",
          explanation_for_inspector: "The system could not identify mandatory blocks on the visible front panel. Please submit back and side packaging surfaces before making a compliance determination.",
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "NOT_DETECTED",
          detected_value: "NONE",
          normalized_value: "mrp_found=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "MRP declaration not found on visible front surface. Never auto-flagged as violation when package coverage is incomplete.",
          explanation_for_inspector: "Price declaration was not detected on the submitted front panel. Please upload the back panel where MRP is typically stamped.",
          evidence: { raw_ocr_text: "[Not found on front panel]" },
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-06",
          status: "NOT_DETECTED",
          detected_value: "NONE",
          normalized_value: "date_found=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Date declaration not found on submitted panel.",
          explanation_for_inspector: "Manufacture date not detected on front panel.",
          rule_version: RULE_METADATA["REQ-MVP-06"],
        },
        {
          rule_id: "REQ-MVP-07",
          status: "NOT_DETECTED",
          detected_value: "NONE",
          normalized_value: "consumer_care_found=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Consumer care block not detected on front panel.",
          explanation_for_inspector: "Consumer care details not found on front face.",
          rule_version: RULE_METADATA["REQ-MVP-07"],
        },
        {
          rule_id: "REQ-MVP-08",
          status: "NOT_DETECTED",
          detected_value: "NONE",
          normalized_value: "address_found=false",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "Manufacturer address not detected on front panel.",
          explanation_for_inspector: "Manufacturer address not found on front panel.",
          rule_version: RULE_METADATA["REQ-MVP-08"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 9. ANALYSIS_FAILED (Severely blurred / corrupt package image)
  // ---------------------------------------------------------------------------
  "insp-009": {
    inspection: {
      id: "insp-009",
      created_at: "2026-09-06T14:30:00Z",
      updated_at: "2026-09-06T14:30:45Z",
      status: "FAILED",
      compliance_status: "ANALYSIS_FAILED",
      product_name: "Ultra Clean Detergent Powder",
      brand_name: "Ultra Clean",
      commodity_category: "Detergent",
      inspector_id: "insp_delhi_01",
      image_coverage: { front: true, back: false, side: false, top: false },
      notes: "Camera motion blur prevented OCR character segmentation. Quality check failed.",
      images_count: 1,
      has_extraction: false,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-009-blur",
        inspection_id: "insp-009",
        file_name: "blurry_detergent.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 180000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fee2e2'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23fef2f2' stroke='%239f1239' stroke-width='2'/><text x='300' y='160' font-family='sans-serif' font-size='22' font-weight='bold' fill='%23881337' text-anchor='middle'>ANALYSIS FAILED</text><text x='300' y='210' font-family='sans-serif' font-size='15' fill='%239f1239' text-anchor='middle'>Severe Motion Blur & Low Lighting Detected</text><text x='300' y='250' font-family='sans-serif' font-size='13' fill='%23475569' text-anchor='middle'>OCR engine confidence &lt; 0.20 across all candidate blocks</text></svg>",
        uploaded_at: "2026-09-06T14:30:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-009",
      image_coverage: { front: true, back: false, side: false, top: false },
      raw_ocr_blocks: [],
    },
    compliance: {
      inspection_id: "insp-009",
      overall_status: "ANALYSIS_FAILED",
      summary_counts: {
        total_rules: 15,
        compliant: 0,
        potential_violations: 0,
        needs_manual_review: 0,
        not_applicable: 0,
        not_detected: 0,
        analysis_failed: 15, // Complete pipeline failure
      },
      evaluated_at: "2026-09-06T14:30:45Z",
      engine_version: "v2.0.0-verified",
      rule_results: Object.keys(RULE_METADATA).map((rId) => ({
        rule_id: rId,
        status: "ANALYSIS_FAILED",
        detected_value: "Unreadable",
        normalized_value: "ocr_failure=true",
        detection_confidence: 0.12,
        applicability_confidence: 0.0,
        reason: "Technical vision pipeline failed. Severe motion blur prevented character recognition. No legal determination made.",
        explanation_for_inspector: "The technical pipeline could not extract readable characters from this photograph. Please capture a sharper photograph under proper illumination.",
        rule_version: RULE_METADATA[rId],
      })),
    },
  },

  // ---------------------------------------------------------------------------
  // 10. SMALL PACKAGE EXEMPTION (Weight <= 10g under Rule 26 -> NOT_APPLICABLE)
  // ---------------------------------------------------------------------------
  "insp-010": {
    inspection: {
      id: "insp-010",
      created_at: "2026-09-06T15:00:00Z",
      updated_at: "2026-09-06T15:01:25Z",
      status: "REPORT_GENERATED",
      compliance_status: "NOT_APPLICABLE",
      product_name: "Kashmir Pure Saffron 0.5g",
      brand_name: "Kashmir Gold",
      commodity_category: "Saffron",
      inspector_id: "insp_srinagar_01",
      image_coverage: { front: true, back: true, side: false, top: false },
      notes: "Miniature blister pack 0.5g. Verified Rule 26 small package exemption.",
      images_count: 1,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-010-f",
        inspection_id: "insp-010",
        file_name: "saffron_blister.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 210000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23f8fafc'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%2364748b' stroke-width='2'/><text x='300' y='90' font-family='sans-serif' font-size='22' font-weight='bold' fill='%23334155' text-anchor='middle'>Kashmir Pure Saffron</text><rect x='220' y='160' width='160' height='45' fill='%23f1f5f9' stroke='%2394a3b8'/><text x='300' y='190' font-family='sans-serif' font-size='16' font-weight='bold' fill='%230f172a' text-anchor='middle'>Net Qty: 0.5 g</text></svg>",
        uploaded_at: "2026-09-06T15:00:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-010",
      product_name: { value: "Saffron", raw_text: "Kashmir Pure Saffron", confidence: 0.98 },
      commodity_category: { value: "Saffron", raw_text: "Saffron", confidence: 0.98 },
      net_quantity: { value: 0.5, unit: "g", raw_text: "Net Qty: 0.5 g", confidence: 0.98, location: "front" },
      mrp: { value: 250.0, currency: "₹", tax_inclusivity: true, raw_text: "MRP ₹ 250", confidence: 0.95 },
      image_coverage: { front: true, back: true, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-010",
      overall_status: "NOT_APPLICABLE",
      summary_counts: {
        total_rules: 15,
        compliant: 2,
        potential_violations: 0,
        needs_manual_review: 0,
        not_applicable: 13, // Rule 26 exemption establishes NOT_APPLICABLE
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T15:01:25Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-01",
          status: "NOT_APPLICABLE",
          detected_value: "0.5 g",
          normalized_value: "weight=0.5g; threshold=10.0g",
          detection_confidence: 0.98,
          applicability_confidence: 1.0,
          reason: "Net weight is 0.5 g (equal to or under 10 grams). Exempt from standard retail package declarations under Rule 26(a).",
          explanation_for_inspector: "Package qualifies for the small package exemption under Rule 26(a) (net weight is 10g or less). Standard declarations are not legally required.",
          evidence: { raw_ocr_text: "Net Qty: 0.5 g" },
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "NOT_APPLICABLE",
          detected_value: "0.5 g",
          normalized_value: "rule_26_exempt=true",
          detection_confidence: 0.98,
          applicability_confidence: 1.0,
          reason: "Rule 26 small package exemption applies to entire PCR chapter.",
          explanation_for_inspector: "Exempt under Rule 26(a).",
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-03",
          status: "COMPLIANT",
          detected_value: "0.5 g",
          normalized_value: "unit=g",
          detection_confidence: 0.98,
          applicability_confidence: 1.0,
          reason: "Metric unit 'g' used correctly.",
          explanation_for_inspector: "Metric symbol complies.",
          rule_version: RULE_METADATA["REQ-MVP-03"],
        },
        {
          rule_id: "REQ-MVP-10",
          status: "NOT_APPLICABLE",
          detected_value: "Saffron",
          normalized_value: "is_pan_masala=false",
          detection_confidence: 0.99,
          applicability_confidence: 1.0,
          reason: "Not Pan Masala. Rule 26 exemption remains valid.",
          explanation_for_inspector: "Standard small-package exemption stands.",
          rule_version: RULE_METADATA["REQ-MVP-10"],
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 11. PAN MASALA ROUTED (Exemption disabled by G.S.R. 881(E))
  // ---------------------------------------------------------------------------
  "insp-011": {
    inspection: {
      id: "insp-011",
      created_at: "2026-09-06T15:30:00Z",
      updated_at: "2026-09-06T15:31:40Z",
      status: "ANALYSIS_COMPLETE",
      compliance_status: "COMPLIANT",
      product_name: "Rajeshwar Premium Pan Masala 4g",
      brand_name: "Rajeshwar",
      commodity_category: "Pan Masala",
      inspector_id: "insp_kanpur_03",
      image_coverage: { front: true, back: true, side: false, top: false },
      notes: "Small sachet 4g. Enforced G.S.R. 881(E) 2025 amendment disabling small-pack exemption.",
      images_count: 2,
      has_extraction: true,
      has_result: true,
    },
    images: [
      {
        evidence_id: "ev-011-f",
        inspection_id: "insp-011",
        file_name: "pan_masala_sachet.jpg",
        image_type: "front",
        mime_type: "image/jpeg",
        file_size_bytes: 240000,
        url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='400' viewBox='0 0 600 400'><rect width='600' height='400' fill='%23fef2f2'/><rect x='40' y='30' width='520' height='340' rx='8' fill='%23ffffff' stroke='%23dc2626' stroke-width='2'/><text x='300' y='80' font-family='sans-serif' font-size='22' font-weight='bold' fill='%23991b1b' text-anchor='middle'>Rajeshwar Premium Pan Masala</text><text x='300' y='120' font-family='sans-serif' font-size='16' font-weight='bold' fill='%23b91c1c' text-anchor='middle'>Net Wt: 4 g | MRP ₹ 5.00 incl. of all taxes</text><text x='300' y='180' font-family='sans-serif' font-size='13' fill='%23475569' text-anchor='middle'>G.S.R. 881(E) Router: Small Package Exemption Under Rule 26 Disallowed</text></svg>",
        uploaded_at: "2026-09-06T15:30:10Z",
      },
    ],
    extraction: {
      inspection_id: "insp-011",
      product_name: { value: "Pan Masala", raw_text: "Rajeshwar Premium Pan Masala", confidence: 0.97 },
      commodity_category: { value: "Pan Masala", raw_text: "Pan Masala", confidence: 0.99 },
      net_quantity: { value: 4.0, unit: "g", raw_text: "Net Wt: 4 g", confidence: 0.96, location: "front" },
      mrp: { value: 5.0, currency: "₹", tax_inclusivity: true, raw_text: "MRP ₹ 5.00 inclusive of all taxes", confidence: 0.95 },
      date_of_manufacture: { month: "09", year: "2026", raw_text: "09/2026", confidence: 0.94 },
      manufacturer: { premises: "Plot 10", street: "Fazalganj", city: "Kanpur", state: "Uttar Pradesh", pin_code: "208012", raw_text: "Rajeshwar Products, Kanpur 208012", confidence: 0.95 },
      consumer_care: { phone: "0512223344", email: "support@rajeshwarpm.com", raw_text: "Helpline: 0512223344", confidence: 0.91 },
      image_coverage: { front: true, back: true, side: false, top: false },
    },
    compliance: {
      inspection_id: "insp-011",
      overall_status: "COMPLIANT",
      summary_counts: {
        total_rules: 15,
        compliant: 11,
        potential_violations: 0,
        needs_manual_review: 2,
        not_applicable: 2,
        not_detected: 0,
        analysis_failed: 0,
      },
      evaluated_at: "2026-09-06T15:31:40Z",
      engine_version: "v2.0.0-verified",
      rule_results: [
        {
          rule_id: "REQ-MVP-10",
          status: "COMPLIANT",
          detected_value: "Pan Masala (4 g declared)",
          normalized_value: "commodity=Pan Masala; exemption_bypassed=true",
          detection_confidence: 0.99,
          applicability_confidence: 1.0,
          reason: "Under G.S.R. 881(E) (Second Amendment 2025), Pan Masala is explicitly excluded from small-package exemptions under Rule 26(a). Full declarations verified.",
          explanation_for_inspector: "Pan Masala product correctly bypasses small-package exemptions and carries all standard retail declarations as mandated by G.S.R. 881(E).",
          evidence: { raw_ocr_text: "Rajeshwar Premium Pan Masala" },
          rule_version: RULE_METADATA["REQ-MVP-10"],
        },
        {
          rule_id: "REQ-MVP-01",
          status: "COMPLIANT",
          detected_value: "Full declarations present",
          detection_confidence: 0.96,
          applicability_confidence: 1.0,
          reason: "Mandatory declarations present on sachet.",
          explanation_for_inspector: "Declarations verified despite 4g pack size.",
          rule_version: RULE_METADATA["REQ-MVP-01"],
        },
        {
          rule_id: "REQ-MVP-02",
          status: "COMPLIANT",
          detected_value: "MRP ₹ 5.00 inclusive of all taxes",
          detection_confidence: 0.95,
          applicability_confidence: 1.0,
          reason: "MRP format complies.",
          explanation_for_inspector: "Price declaration complies with Rule 2(m).",
          rule_version: RULE_METADATA["REQ-MVP-02"],
        },
        {
          rule_id: "REQ-MVP-14",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "Quiet zone visual aid",
          detection_confidence: 0.86,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Verify quiet zone on 4g numeral.",
          rule_version: RULE_METADATA["REQ-MVP-14"],
        },
        {
          rule_id: "REQ-MVP-15",
          status: "NEEDS_MANUAL_REVIEW",
          detected_value: "High contrast red/gold",
          detection_confidence: 0.88,
          applicability_confidence: 1.0,
          reason: "Visual aid.",
          explanation_for_inspector: "Confirm visual legibility.",
          rule_version: RULE_METADATA["REQ-MVP-15"],
        },
      ],
    },
  },
};

export const MOCK_DASHBOARD_SUMMARY = {
  total_inspections: 11,
  compliant_inspections: 3,
  potential_violations: 2,
  needs_manual_review: 4,
  not_applicable: 1,
  analysis_failed: 1,
  pending_analysis: 0,
  top_violated_rules: [
    { rule_id: "REQ-MVP-06", count: 3, rule_name: "Date Declaration & Overwriting Proviso" },
    { rule_id: "REQ-MVP-07", count: 2, rule_name: "Consumer Care Contact Details" },
    { rule_id: "REQ-MVP-02", count: 2, rule_name: "Maximum Retail Price (MRP) Layout" },
    { rule_id: "REQ-MVP-01", count: 1, rule_name: "Mandatory Declaration Presence" },
    { rule_id: "REQ-MVP-05", count: 1, rule_name: "Prohibited Quantity Qualifiers" },
  ],
  recent_inspections: Object.values(MOCK_FIXTURES).map((f) => f.inspection),
};
